### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bkinney** [mcjelewis/threadz#2]
It seems that trying to view an unthreaded discussion in Threadz causes errors. No big surprise there, but my bad luck to pick a course with unthreaded discussion for testing! I would suggest filtering out unthreaded discussions from the discussion dropdown menu. It's pretty confusing when the data just fails to load with no indication of why. Actually, I could see it being valuable to leave the discussions in there, but when they are selected, the tabs don't activate, so you have to mess in the console even to see that the data tables load up just fine.

**Comment by mcjelewis** [comment]
Threaded discussion should be viewable. The user network should show a node for each user, just no connections between them. I'm not sure why you're getting a failed data load.
